gText_Birch_Welcome::
	.string "-FROM THE DESK OF STEVEN STONE-\p"
	.string "I hope this letter finds you well.\p"
	.string "I had to rely on my father's Skarmory,\n"
	.string "and he's 52 years old and blind.\p"
	.string "Sharp old bird, though.\p"
	.string "My name is Steven.\p"
	.string "I represent the Devon Corporation\n"
	.string "and would like to offer you a job.\p"
	.string "I need someone to be my eyes and\n"
	.string "ears in the HOLON region.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "You'll notice this Chimecho looks\n"
	.string "different than you might expect.\p"
	.string "Delta Chimecho has inherited\n"
	.string "the Steel type, changing its\l"
	.string "appearance and powers.\p"
	.string "Believe it or not, the HOLON region\n"
	.string "is the only known home to these\l"
	.string "special Pokemon, and our scientists\l"
	.string "are tirelessly searching for\l"
	.string "the reason why.\p"
	.string "There's a lot about HOLON we still\n"
	.string "don't understand.\p"
	.string "Your mission, should you choose to\n"
	.string "accept it, is to join our next\l"
	.string "expedition to the HOLON region\l"
	.string "and help uncover its secrets.\p"
	.string "A boat will be ready for you\n"
	.string "Friday at 6PM out of Lilycove\l"
	.string "City Harbor.\p"
	.string "Take the ride, and meet up with\n"
	.string "Professor Cozmo in Archtide Town.\p"
	.string "Good luck, and hey...\p"
	.string "Have a little fun.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now then.\n"
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "How do you identify?$"

gText_Birch_WhatsYourName::
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "So you're {PLAYER}{KUN}, the one who\n"
	.string "answered my letter.\p"
	.string "I'm glad you came.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right. Are you ready?\p"
	.string "Your own journey through HOLON is\n"
	.string "about to begin.\p"
	.string "Step ashore, and see this strange\n"
	.string "region for yourself.\p"
	.string "I'll be waiting. Come find me when\n"
	.string "you're ready.\p"
	.string "$"
